# Generated by Django 3.0.8 on 2020-07-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('width', models.PositiveIntegerField(blank=True)),
                ('height', models.PositiveIntegerField(blank=True)),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
